### ISSUE TITLE
Dont show heartrate if it isn't there

### ISSUE THREAD

**Issue by wschoot** [torandi/garmin-wrapped#2]
Hi!

Given the slide below, it might be better not to show the avg heartrate at all. What do you think?

![image](https://github.com/torandi/garmin-wrapped/assets/3919193/23ce5bda-261c-44e8-8668-b9fbce4558d4)

**Comment by torandi** [comment]
Yeah, I agree. I'll hide it if it's zero.

**Comment by torandi** [comment]
Fixed in latest commit
