### ISSUE TITLE
Elevation gain unclear / weirdly formatted

### ISSUE THREAD

**Issue by wschoot** [torandi/garmin-wrapped#3]
Hi,

Given the slide below, the 15km907m is the total elevation gained. The formatting looks a bit weird. Better would probably be "15907 meters" or something like "Almost 16 km"

It's also not very clear that this number indeed IS the elevation gained.

<img width="593" alt="image" src="https://github.com/torandi/garmin-wrapped/assets/3919193/90cbc161-344a-4976-bc73-a08ebf0d8e6f">

**Comment by torandi** [comment]
Yeah, it should add a description to that. I thought I did, but maybe that was a different slide.

And good point about rounding of into closest kilometer.

**Comment by torandi** [comment]
Fixed in latest commit
