### ISSUE TITLE
"Minutes" are sometimes on the next line, making the graph look strange

### ISSUE THREAD

**Issue by wschoot** [torandi/garmin-wrapped#4]
Hi,

Given the slide below, the "minutes" part sometimes gets cut off and placed on the next line, just below the month. An improvement could to use another notation (1d, 8hrs, 51min) or make that column a bit wider.

<img width="1003" alt="image" src="https://github.com/torandi/garmin-wrapped/assets/3919193/52183d98-141a-48c4-a9c9-1a27c90094f9">

**Comment by torandi** [comment]
Aaahh, good catch. None of my data was more than a day :)

I think as you say, make the notations shorter is probably the easier option. I'll look into it tonight.

**Comment by torandi** [comment]
Fixed in latest commit

**Comment by wschoot** [comment]
Nice, looks way cleaner now.

![image](https://github.com/torandi/garmin-wrapped/assets/3919193/2495b7ea-a945-4ae4-bc1f-32fc0889a75c)
