### ISSUE TITLE
Dont show non-distance sports on the distance-slide

### ISSUE THREAD

**Issue by wschoot** [torandi/garmin-wrapped#5]
Hi,

Given this slide, wouldn't it make sense to remove the strength and racket sports as they're without distance/gps ?

<img width="784" alt="image" src="https://github.com/torandi/garmin-wrapped/assets/3919193/f8eb8f92-472e-475c-b879-f3c66e53ce0c">

**Comment by torandi** [comment]
Yupp, good point, will do that.

**Comment by torandi** [comment]
Fixed in latest commit

**Comment by wschoot** [comment]
Something went wrong here. Previously, I had 1070 kms of walking, now I have 171km of walking. Also, my alpine skiing for last year increased by 1 km

![image](https://github.com/torandi/garmin-wrapped/assets/3919193/bbc95913-7f6e-4faa-a9d7-27385561c4fc)

**Comment by torandi** [comment]
Ah. I tried to do some formating of numbers (ie 1070km => 1 070km), but I didn't think of the case where the hundreds was 0.

I think the alpine skiing increas was just that I changed from rounding down to rounding to closest km

**Comment by torandi** [comment]
Fixed now :)

**Comment by wschoot** [comment]
Confirmed!
