### ISSUE TITLE
Activity vs Activities

### ISSUE THREAD

**Issue by wschoot** [torandi/garmin-wrapped#7]
Hi!

As I only played padel once in 2023, the slide looks like this. Should we make it "1 activity" instead of "1 activities" ? Also, if there's just one activity in the summary, an average duration make no real sense as it will be the same as the total.

![image](https://github.com/torandi/garmin-wrapped/assets/3919193/09ade023-20c9-48ba-9f3f-45d1769be67a)

**Comment by torandi** [comment]
Yeah, good point. I added a condition to not include any single activity sports from having their own summary page.
